#!/usr/bin/env node
/**
 * Local frontend validator - `npm run validate:ui`
 *
 * Two layers:
 *
 *  1. Business rules. `scripts/ui-smoke-entry.ts` drives the real lib modules
 *     the pages use (`engine`, `demo`, `mutations`, `permissions`, `format`) in
 *     LOCAL DEMO MODE and asserts the same rules that
 *     `supabase/tests/01_rls_and_business_rules.sql` proves for PostgreSQL:
 *     server-side pricing, the stock-ledger invariant, the payment ceiling, the
 *     udhaar credit limit, idempotent billing and the owner/manager/cashier
 *     ladder. It is bundled with esbuild (the same bundler Vite uses) so the
 *     TypeScript actually under test is the code that ships.
 *
 *  2. The running dev server. If Vite is listening on http://localhost:5173 the
 *     entry document and every app module are fetched and checked for HTTP 200,
 *     which proves the app boots end to end on localhost. When the server is not
 *     running this layer reports "skipped" instead of failing.
 *
 * Usage:
 *   npm run validate:ui
 */
import { mkdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import esbuild from 'esbuild';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const outDir = path.join(root, 'node_modules', '.cache', 'ksm');
const outFile = path.join(outDir, 'ui-smoke.mjs');

const colours = process.stdout.isTTY
  ? {
      green: (s) => `\u001b[32m${s}\u001b[0m`,
      red: (s) => `\u001b[31m${s}\u001b[0m`,
      dim: (s) => `\u001b[2m${s}\u001b[0m`,
      bold: (s) => `\u001b[1m${s}\u001b[0m`,
    }
  : { green: (s) => s, red: (s) => s, dim: (s) => s, bold: (s) => s };

/** Modules the shell loads. Each must answer 200 for the app to boot. */
const APP_MODULES = [
  '/src/main.tsx',
  '/src/App.tsx',
  '/src/app/store.tsx',
  '/src/app/shell.tsx',
  '/src/lib/engine.ts',
  '/src/lib/demo.ts',
  '/src/lib/mutations.ts',
  '/src/lib/permissions.ts',
  '/src/pages/Login.tsx',
  '/src/pages/Dashboard.tsx',
  '/src/pages/Billing.tsx',
  '/src/pages/Products.tsx',
  '/src/pages/Purchases.tsx',
  '/src/pages/Sales.tsx',
  '/src/pages/Customers.tsx',
  '/src/pages/Reports.tsx',
  '/src/pages/Settings.tsx',
];

async function probeDevServer() {
  const base = process.env.KSM_DEV_URL || 'http://localhost:5173';
  const checks = [];
  const targets = ['/', ...APP_MODULES];
  for (const target of targets) {
    try {
      const res = await fetch(base + target, { signal: AbortSignal.timeout(5000) });
      checks.push({ target, ok: res.ok, detail: `HTTP ${res.status}` });
    } catch (error) {
      checks.push({
        target,
        ok: false,
        detail: error?.name === 'TimeoutError' ? 'timed out' : String(error?.message ?? error),
      });
    }
  }
  const reachable = checks.some((c) => c.target === '/' && c.ok);
  return { base, reachable, checks };
}

async function build() {
  await mkdir(outDir, { recursive: true });
  await esbuild.build({
    entryPoints: [path.join(here, 'ui-smoke-entry.ts')],
    outfile: outFile,
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node20',
    logLevel: 'warning',
    banner: { js: '// generated by scripts/validate-ui.mjs - do not edit' },
  });
}

async function main() {
  console.log(colours.bold('[1/3] Bundling the smoke scenario with esbuild...'));
  await build();

  console.log(colours.bold('[2/3] Running the in-browser working model checks...'));
  const { runUiSmoke } = await import(pathToFileURL(outFile).href);
  const results = runUiSmoke();
  for (const r of results) {
    console.log(
      `  ${r.ok ? colours.green('PASS') : colours.red('FAIL')}  ${r.name}` +
        (r.detail ? colours.dim(` - ${r.detail}`) : ''),
    );
  }
  const failed = results.filter((r) => !r.ok);
  console.log(
    failed.length === 0
      ? colours.green(`\n  ${results.length}/${results.length} working-model checks passed`)
      : colours.red(`\n  ${results.length - failed.length}/${results.length} checks passed`),
  );

  console.log(colours.bold('[3/3] Probing the Vite dev server on localhost...'));
  const dev = await probeDevServer();
  if (!dev.reachable) {
    console.log(
      colours.dim(`  skipped: no dev server on ${dev.base} - run \`npm run dev\` and try again`),
    );
  } else {
    for (const c of dev.checks) {
      console.log(
        `  ${c.ok ? colours.green('PASS') : colours.red('FAIL')}  ${c.target}` + colours.dim(` - ${c.detail}`),
      );
    }
    const down = dev.checks.filter((c) => !c.ok);
    console.log(
      down.length === 0
        ? colours.green(`\n  ${dev.checks.length}/${dev.checks.length} app modules served on ${dev.base}`)
        : colours.red(`\n  ${dev.checks.length - down.length}/${dev.checks.length} app modules served`),
    );
  }

  await rm(outDir, { recursive: true, force: true }).catch(() => {});

  const devFailed = dev.reachable ? dev.checks.filter((c) => !c.ok).length : 0;
  if (failed.length > 0 || devFailed > 0) process.exitCode = 1;
}

main().catch(async (error) => {
  await rm(outDir, { recursive: true, force: true }).catch(() => {});
  console.error(error);
  process.exitCode = 1;
});
